NoSuchCheckerException: Remove unused constructors
Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: I4f278748abf9565d3cb1b617a4ca686855f71bf0